server:
  port: ${config.server.port:7077}

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.100.221:3306/bunin
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jersey:
    application-path: bunin/api
  data:
    mongodb:
      uri: mongodb://192.168.100.221:27017/bunin